#!/bin/bash
make clean
make runner.ign
IGNITION_CONFIG="./runner.ign"

source .env
SERVER_NAME="runner"

export HCLOUD_TOKEN="$HCLOUD_TOKEN"

STREAM="stable"     # or "testing", "next"
ARCH="x86"          # or "arm"

IMAGE_ID="$(hcloud image list \
    --type=snapshot \
    --selector=os=fedora-coreos \
    --output json \
    | jq -r '.[0].id')"
OLD_SERVER_ID="$(hcloud server list \
    --selector=name=$SERVER_NAME \
    --output json \
    | jq -r '.[0].id')"
echo "$SERVER_NAME"

if [ -n $OLD_SERVER_ID ]; then
  echo "Shutting down old runner: $OLD_SERVER_ID"
  hcloud server shutdown \
    --wait \
    --wait-timeout 300s \
    "$OLD_SERVER_ID"

  echo "Deleting old runner"
  hcloud server delete "$OLD_SERVER_ID"
fi;

echo "Creating replacement runner: $SERVER_NAME"
hcloud server create \
    --name "$SERVER_NAME" \
    --type "cx22" \
    --datacenter "$DATACENTER" \
    --image "$IMAGE_ID" \
    --label name=$SERVER_NAME \
    --user-data-from-file "$IGNITION_CONFIG"
