#!/bin/bash
make clean
make

STREAM="stable"

#IMAGE_NAME=$(podman run --pull=always --rm -v "${HOME}/.local/share/libvirt/images/:/data" -w /data \
#  quay.io/coreos/coreos-installer:release download -s $STREAM -p qemu -f qcow2.xz --decompress)
IMAGE_NAME="fedora-coreos-42.20250427.3.0-qemu.x86_64.qcow2"
IGNITION_CONFIG="$(pwd)/config.ign"
IMAGE="${HOME}/.local/share/libvirt/images/${IMAGE_NAME}"
VM_NAME="fcos-test-01"
VCPUS="2"
RAM_MB="2048"
STREAM="stable"
DISK_GB="10"

# For x86 / aarch64,
IGNITION_DEVICE_ARG=(--qemu-commandline="-fw_cfg name=opt/com.coreos/config,file=${IGNITION_CONFIG}")

# For s390x / ppc64le,
# IGNITION_DEVICE_ARG=(--disk path="${IGNITION_CONFIG}",format=raw,readonly=on,serial=ignition,startup_policy=optional)

# Setup the correct SELinux label to allow access to the config
chcon --verbose --type svirt_home_t ${IGNITION_CONFIG}

if [ ! -e ./persistent.qcow2 ]; then
  qemu-img create -f qcow2 persistent.qcow2 10G
fi

sudo virt-install --connect="qemu:///system" --name="${VM_NAME}" --vcpus="${VCPUS}" --memory="${RAM_MB}" \
        --os-variant="fedora-coreos-$STREAM" --import --graphics=none \
        --disk="size=${DISK_GB},backing_store=${IMAGE}" \
        --disk="./persistent.qcow2" \
        --network bridge=virbr0 "${IGNITION_DEVICE_ARG[@]}"
